name: Flutter Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.x' # Use the latest stable version of Flutter 3
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Run analyzer
      run: flutter analyze

    - name: Run tests
      run: flutter test

    - name: Build Android APK
      run: flutter build apk --debug # Building debug APK for faster build and demonstration
